version: '3.8'

services:
  traefik:
    image: traefik:v3.2.3
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - CF_DNS_API_TOKEN=$CF_DNS_API_TOKEN
    volumes:
      # static config file
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      # for certs
      - ./data/certs/:/var/traefik/certs/:rw
      # dynamic config file
      - ./dynamic_config/:/etc/traefik/dynamic/:ro
    restart: always
