global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: INFO
api:
  dashboard: true
  insecure: true
  debug: true
entryPoints:
  web:
    address: :80
  websecure:
    address: :443
certificatesresolvers:
  cloudflare:
    acme:
      email: "yourEmail@gmail.com"
      storage: /var/traefik/certs/cloudflare-acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1"
        delayBeforeCheck: 30
providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true
